name: slides
adopt-info: slides
summary: Slides in your terminal.
description: |
  Slides in your terminal.
  
  Usage:
    slides <file.md> [flags]

  Flags:
    -h, --help   help for slides
    
license: MIT

base: core22
grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  
assumes:
  - command-chain
  
apps:
  slides:
    command: bin/slides
    command-chain: 
      - bin/homeishome-launch     
    plugs:
      - home
      - ssh-keys
      - ssh-public-keys
      - network
      - network-bind
      
parts:
  slides:
    source: https://github.com/maaslalani/slides
    source-type: git
    plugin: go
    build-snaps:
      - go
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     
