name: slides
adopt-info: slides
summary: Slides in your terminal.
description: |
  Slides in your terminal.
  
  Usage:
    slides <file.md> [flags]

  Flags:
    -h, --help   help for slides
    
license: MIT

base: core20
grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  
assumes:
  - command-chain
  
apps:
  slides:
    command: bin/slides
    command-chain: 
      - bin/homeishome-launch     
    plugs:
      - home
      
parts:
  slides:
    source: https://github.com/maaslalani/slides
    source-type: git
    plugin: go
    go-channel: latest/stable

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    

    override-build: |
      version=$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)
      shortCommit=git rev-parse --short HEAD
      commitDate=git show -s --format=%cd --date=short

      baseFlag="-X github.com/maaslalani/slides/internal/version"
      ldFlags="${baseFlag}.Version=${version}"
      ldFlags="${ldFlags} ${baseFlag}.ShortCommit=${shortCommit}"
      ldFlags="${ldFlags} ${baseFlag}.CommitDate${commitDate}"

      GO111MODULE=on CGO_ENABLED=0 go build -trimpath -ldflags "${ldFlags" -o slides main.go

      chmod +x slides
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv slides $SNAPCRAFT_PART_INSTALL/bin

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     
